services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web
    ports:
      - '3000:3000'
    environment:
      - VITE_AUTH0_DOMAIN=dev-j2yritfv6ayfwyki.us.auth0.com
      - VITE_AUTH0_CLIENTID=3xsQdxnXlUvO9sGBlhYL9NJTWE4qkJ9I
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
